### PR TITLE
🪧 Hover on Tag in `<TagList />` shows description

### LINKED ISSUE #141: Tooltip shows Tag description
Show a tooltip (either the component or probably the OS's) that includes the description of the tag when the user hovers over it in the Tag Dropdown.

### PR DESCRIPTION
**Pull request by cal-overflow**
Closes #141

### CODE REVIEW

**Comment by cal-overflow** [comment]
I think you're on the wrong repo 👀

**Comment by mamoore1440** [comment]
bruh

**Comment by mamoore1440** [comment]
ugh

**Comment by cal-overflow** [comment]
> bruh

Agreed.

I'm probably just gonna make my changes on another branch rather than dealing with reverting commits and all that lol.

**Comment by mamoore1440** [comment]
Sorry about this. I am going to sever my econ blog from the template. I don't know how to pull it up to date i guess😔

**Comment by cal-overflow** [comment]
All good. We can take a look at it together sometime.

I'll also add a "Updating template" section or something to the template's README.

**Pull request closed without merging**
